Repository ublue-os/akmods, pull requests merged in 2025-05, with the labels that each got.

#331 chore(ci): stop building unused akmods images
  .github/workflows/build-40.yml
  .github/workflows/build-41.yml
  .github/workflows/build-bazzite.yml
  .github/workflows/reusable-build.yml
Labels: size:M, lgtm

#332 chore: fixup bazzite kernel build args
  .github/workflows/build-bazzite.yml
Labels: size:XS, lgtm

#333 chore: don't build bazzite kernel for F41
  .github/workflows/build-41.yml
Labels: size:XS, lgtm

#334 fix: temporary pin of coreos-stable to 6.13.8-200.fc41.x86_64
  .github/actions/get-kernel-version/action.yml
  build_files/shared/build-prep.sh
Labels: size:XS, lgtm

#335 chore: bump zfs to 2.3
  Containerfile.zfs
Labels: dependencies, size:XS, lgtm

#337 docs: bring README into sync with reality
  README.md
Labels: documentation, size:L, lgtm

#322 feat: add centos 10 support
  .github/actions/get-kernel-version/action.yml
  .github/workflows/build-centos.yml
  .github/workflows/reusable-build.yml
  build_files/shared/build-prep.sh
  build_files/shared/test-prep.sh
  build_files/zfs/build-kmod-zfs.sh
  fetch-kernel.sh
Labels: enhancement, size:L, lgtm

#339 feat: remove xpadneo
  Containerfile.common
  README.md
  build_files/common/build-kmod-xpadneo.sh
Labels: documentation, enhancement, size:S, lgtm

#338 fix: remove coreos-stable kernel pin, unleash Fedora 42
  .github/actions/get-kernel-version/action.yml
Labels: autorelease: pending, size:XS, lgtm
