Repository ublue-os/akmods, pull requests merged in 2025-04, with the labels that each got.

#319 chore(README): fix dead URLs
  README.md
Labels: documentation, size:XS, lgtm

#320 chore: enable openrazer for Fedora 42
  build_files/common/build-kmod-openrazer.sh
Labels: size:XS, lgtm

#321 chore: enable Bazzite and CoreOS kernels
  .github/workflows/build-42.yml
  .github/workflows/build-bazzite.yml
Labels: size:XS

#323 fix: specify crc32 integrity check when recompressing kmods
  .github/workflows/reusable-build.yml
  build_files/shared/build-prep.sh
  build_files/shared/check-signatures.sh
  build_files/shared/dual-sign.sh
  build_files/shared/test-prep.sh
  build_files/zfs/dual-sign-zfs.sh
Labels: bug, size:M, lgtm
