Repository ublue-os/akmods, pull requests merged in 2025-03, with the labels that each got.

#310 feat(bazzite): add webhook for bazzite kernel and update url
  .github/actions/get-kernel-version/action.yml
  .github/workflows/build-bazzite.yml
  .github/workflows/reusable-build.yml
  fetch-kernel.sh
Labels: enhancement, size:M, lgtm

#311 chore(extra): remove extra from kernels other than bazzite, update readme
  .github/workflows/reusable-build.yml
  README.md
Labels: documentation, size:S, lgtm

#314 chore: update README badges
  README.md
Labels: documentation, size:XS, lgtm

#316 chore: pin actions to their hashes
  .github/workflows/cleanup.yml
  .github/workflows/release-please.yml
  .github/workflows/reusable-build.yml
Labels: size:S, lgtm
